spring:
  sleuth:
    sampler:
      probability: 1.0
    baggage:
      correlation-fields: x-request-id
    propagation:
      type: b3
  application:
    name: ts-station-service
  data:
    mongodb:
      # uri: mongodb://ts-station-mongo:27017/ts
      host: ts-station-mongo
      #      username: user
      #      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017

# HTTP Server
server:
 port: 12345  # HTTP (Tomcat) port
