# HTTP Server
server:
  port: 14569 # HTTP (Tomcat) port

spring:
  main:
    banner-mode: "off"
    lazy-initialization: true
  sleuth:
    sampler:
      probability: 1.0
    baggage:
      correlation-fields: x-request-id
    propagation:
      type: b3
  application:
    name: ts-preserve-other-service
