spring:
  main:
    banner-mode: "off"
    lazy-initialization: true
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
    baggage:
      correlation-fields: 
        - x-request-id
      remote-fields:
        - x-request-id
    propagation:
      type: 
        - W3C
  application:
    name: ts-config-service
  data:
    mongodb:
      host: ts-config-mongo
      #       username: user
      #       password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017

# HTTP Server
server:
  port: 15679 # HTTP (Tomcat) port
