server:
  port: 16115

spring:
  sleuth:
    sampler:
      probability: 1.0
    baggage:
      correlation-fields: x-request-id
    propagation:
      type: b3
  application:
    name: ts-admin-user-service


#opentracing:
#  jaeger:
#    udp-sender:
#      host: jaeger
#      port: 6831