server:
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always
  port: 15678 # HTTP (Tomcat) port

spring:
  main:
    banner-mode: "off"
    lazy-initialization: true
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
    baggage:
      correlation-fields: 
        - x-request-id
      remote-fields:
        - x-request-id
    propagation:
      type: 
        - W3C
    zipkin:
      enabled: false

  application:
    name: ts-verification-code-service
