spring:
  main:
    banner-mode: "off"
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
    baggage:
      correlation-fields: 
        - x-request-id
      remote-fields:
        - x-request-id
    propagation:
      type: 
        - W3C
  application:
    name: ts-route-service
  data:
    mongodb:
      host: ts-route-mongo
      #      username: user
      #      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017

# HTTP Server
server:
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always
  port: 11178 # HTTP (Tomcat) port
