server:
  port: 16113

spring:
  sleuth:
    sampler:
      probability: 1.0
    baggage:
      correlation-fields: x-request-id
    propagation:
      type: b3
  application:
    name: ts-admin-route-service
