server:
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always
  port: 12340

spring:
  application:
    name: ts-auth-service
  main:
    banner-mode: "off"
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
    baggage:
      correlation-fields: 
        - x-request-id
      remote-fields:
        - x-request-id
    propagation:
      type:
        - W3C
  data:
    mongodb:
      host: ts-auth-mongo
      database: ts-auth-mongo
      port: 27017
