server:
  port: 16112

spring:
  main:
    banner-mode: "off"
    lazy-initialization: true
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
    baggage:
      correlation-fields: 
        - x-request-id
      remote-fields:
        - x-request-id
    propagation:
      type: 
        - B3
        - W3C
  application:
    name: ts-admin-order-service
