# HTTP Server
server:
  port: 18886 # HTTP (Tomcat) port

spring:
  main:
    banner-mode: "off"
    lazy-initialization: true
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
    baggage:
      correlation-fields: 
        - x-request-id
      remote-fields:
        - x-request-id
    propagation:
      type: 
        - B3
        - W3C
  application:
    name: ts-rebook-service
#  rabbitmq:
#    host: rabbitmq
#    listener:
#      retry:
#        enabled: false
#        max-attempts: 1
#    template:
#      retry:
#        enabled: false
#        max-attempts: 1

#  cloud:
#    stream:
#      bindings:
#        output:
#          group: queue-group-rebook
#          destination: ts-rebook-service-queue-output
#          contentType: text/plain
#          binder: rabbit
